# Generated by Django 6.0.7 on 2026-08-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_set_timetable_alter_department_code_and_more'),
        ('users', '0002_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.set'),
        ),
    ]
