# Generated by Django 6.0.7 on 2026-08-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_hall_level_semester_course_timetable_timetableentry'),
        ('users', '0003_alter_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
