# Generated by Django 6.0.7 on 2026-08-07 03:55

from django.db import migrations



def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for name in ["Admin", "Student", "Lecturer"]:
        Group.objects.get_or_create(name=name)
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_level_alter_user_reg_number'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
