# Generated by Django 6.0.7 on 2026-08-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260807_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
