# Generated by Django 6.0.7 on 2026-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarenode',
            name='name',
            field=models.CharField(default='University-name_School-name_Department-name_Device-id', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hardwarenode',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
