# Generated by Django 6.0.7 on 2026-08-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_hardwarenode_name_and_more'),
        ('entities', '0006_timetableentryschedule_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwarenode',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hardwarenode',
            name='school',
        ),
        migrations.RemoveField(
            model_name='hardwarenode',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='hardwarenode',
            name='university',
        ),
        migrations.AddField(
            model_name='hardwarenode',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hardware_nodes', to='entities.set'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FingerprintStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.PositiveIntegerField()),
                ('hardware_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_stamps', to='attendance.hardwarenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hardware_node', 'fingerprint_id'), name='unique_fingerprint_per_hardware_node'), models.UniqueConstraint(fields=('user', 'hardware_node'), name='unique_user_fingerprint_per_hardware_node')],
            },
        ),
    ]
