# Generated by Django 6.0.7 on 2026-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_hardwarenode_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarenode',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
