# Generated by Django 6.0.7 on 2026-08-10 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name', 'Lecturer')), related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(related_name='courses', to='entities.department'),
        ),
        migrations.AddField(
            model_name='hall',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='entities.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ManyToManyField(related_name='courses', to='entities.level'),
        ),
        migrations.AddField(
            model_name='hall',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='entities.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='entities.school'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_session'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.session'),
        ),
        migrations.AddField(
            model_name='set',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='entities.department'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='entities.department'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.level'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.semester'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='entities.course'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='entities.timetable'),
        ),
        migrations.AddField(
            model_name='timetableentryschedule',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.hall'),
        ),
        migrations.AddField(
            model_name='timetableentryschedule',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Lecturer')), on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableentryschedule',
            name='timetable_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entry_schedules', to='entities.timetableentry'),
        ),
        migrations.AddField(
            model_name='school',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='entities.university'),
        ),
        migrations.AddField(
            model_name='hall',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='entities.university'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='unique_semester_per_session'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('department', 'start_year', 'end_year'), name='unique_set_per_department'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'course', 'day', 'start_time', 'end_time'), name='unique_timetable_entry'),
        ),
        migrations.AddConstraint(
            model_name='timetableentryschedule',
            constraint=models.UniqueConstraint(fields=('timetable_entry', 'date'), name='unique_timetable_entry_schedule'),
        ),
    ]
