# Generated by Django 6.0.7 on 2026-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
