# Generated by Django 6.0.7 on 2026-08-28 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_set_timetable_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
