# Generated by Django 6.0.7 on 2026-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
