# Generated by Django 6.0.7 on 2026-08-30 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_timetableentry_is_one_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentryschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentryschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
