# Generated by Django 6.0.7 on 2026-08-07 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_hall_level_semester_course_timetable_timetableentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'verbose_name': 'Timetable Entry', 'verbose_name_plural': 'Timetable Entries'},
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name', 'Lecturer')), related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
