name: Backend CI

on:
  push:
    paths:
      - "backend/user_service/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/user_service/**"
      - ".github/workflows/backend-ci.yml"
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/user_service
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --locked
      - name: Lint
        run: uv run ruff check .
      - name: Test
        run: uv run pytest -v